### ISSUE TITLE
Cannot export

### ISSUE THREAD

**Issue by GuiMiTomo** [ahigerd/agbplay-gui#1]
Hello, there is a problem when I export a track.
When it finishes, it doesn't show an output file. So, what is wrong?

**Comment by ahigerd** [comment]
I think I'm going to need some more information, because it works for me.

* Can it play the track normally?
* How are you trying to export?
* Can you take a screenshot of the agbplay-gui window after the export is finished?

**Comment by GuiMiTomo** [comment]
Heya, sorry for the laate reply.

- Yes, it can.
- Via "File - Export Selected Track" and via right click - "Export" - neither works!
- ![image](https://github.com/ahigerd/agbplay-gui/assets/76497419/77a3ab96-15e0-4ef2-b9c6-032ae48af0f5)

**Comment by GuiMiTomo** [comment]
Exported to C://. It fixed he problem.

**Comment by ahigerd** [comment]
Try this build: https://github.com/ahigerd/agbplay-gui/releases/tag/v1.0.1

**Comment by GuiMiTomo** [comment]
It fixed more the problem.
